name: Release

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  release-and-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: git config user
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git remote set-url origin https://github-actions[bot]:${{ secrets.GITHUB_TOKEN }}@github.com/mrmilu/front_web_mrmilu.git

      - name: Setup yarn
        run: npm install -g yarn

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: "16"
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Get coverage
        run: yarn test:badges

      - name: Commit changes
        run: |
          git add .
          git commit -m "chore(root): updated test badge"
          git push

      - name: Release & publish
        run: |
          yarn release
          git push --follow-tags origin master
          yarn gitpkg-publish

      - name: Generate docs
        run: |
          yarn generate-docs
          git add .
          git commit -m "chore(root): updated api-docs"
          git push

      - name: Set env for last tag release
        run: echo "LAST_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.19.0
        with:
          channel-id: "C0BJB6V4P"
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "New release :rocket: :rocket:\n*<https://github.com/mrmilu/front_web_mrmilu/blob/master/CHANGELOG.md|${{ env.LAST_TAG }}>*"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
