name: Release

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  release-and-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_ACCESS_TOKEN }}

      - name: git config user
        run: |
          git config --global user.name mrm-dev
          git config --global user.email dev@mrmilu.com

      - name: Setup yarn
        run: npm install -g yarn

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: "16"

      - name: Install dependencies
        run: yarn

      - name: Get coverage
        run: yarn test:badges

      - name: Commit changes
        run: |
          git add .
          git commit -m "chore(root): [skip ci] updated test badge"
          git push

      - name: Release
        run: |
          yarn release
          git push --follow-tags origin master
          yarn build

      - name: Generate docs
        run: |
          yarn generate-docs
          git pull
          git add .
          git commit -m "chore(root): [skip ci] updated api-docs"
          git push

      - name: Publish Hooks
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: "./packages/hooks/package.json"

      - name: Publish Services
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: "./packages/services/package.json"

      - name: Publish Utils
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: "./packages/utils/package.json"

      - name: Publish Network
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: "./packages/network/package.json"

      - name: Set env for last tag release
        run: echo "LAST_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.19.0
        with:
          channel-id: "C0BJB6V4P"
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "New release :rocket: :rocket:\n*<https://github.com/mrmilu/front_web_mrmilu/blob/master/CHANGELOG.md|${{ env.LAST_TAG }}>*"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
