name: Test badges

on:
  push:
    branches: [master]

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |
          yarn,
          yarn test:badges
