name: Test badges

on:
  push:
    branches: [master]

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup yarn
        run: npm install -g yarn

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: "16"
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Get coverage
        run: yarn test:badges

      - name: Commit changes
        uses: EndBug/add-and-commit@v8
        with:
          commit: --no-verify
          message: "chore(root): updated test badge"
